import { Keypair,Connection,PublicKey } from '@solana/web3.js';import bs58 from 'bs58';import { readFileSync,statSync } from 'node:fs';import { Providers } from './providers.mjs';import { USDC,liveConfiguration } from './config.mjs';import { strategy } from './strategy.mjs';import { inspect } from './intelligence.mjs';import { validateIntent,validateQuote,validateTransaction } from './guard.mjs';

const MICRO=1000000n;
function clamp(value,ceiling){return ceiling>0?value<BigInt(ceiling)?value:BigInt(ceiling):value}
function asUsd(raw){return Number(raw)/1e6}

export class Signer{
constructor(c,store){this.c=c;this.s=store;this.p=new Providers(c);this.key=null;this.busy=false;let bytes;if(c.signerEnabled&&c.keyBase64){bytes=Buffer.from(c.keyBase64,'base64');if(bytes.length!==64)throw Error('Invalid base64 keypair length')}else if(c.signerEnabled&&c.keyPath){if(statSync(c.keyPath).mode&0o077)throw Error('Key file must not be group/world readable');const b=JSON.parse(readFileSync(c.keyPath,'utf8'));if(!Array.isArray(b)||b.length!==64)throw Error('Invalid keypair file');bytes=Uint8Array.from(b)}if(bytes)this.key=Keypair.fromSecretKey(bytes);this.wallet=this.key?.publicKey.toBase58()??null;this.p.connection=new Connection(c.rpc,'confirmed')}

async riskLimits(holdings=null){
  if(!this.wallet)return{walletUsdcRaw:0n,trackedExposureRaw:0n,equityRaw:0n,effectiveBankrollRaw:0n,maxOrderRaw:0n,maxDailyRaw:0n,maxLossRaw:0n,portfolioRaw:0n};
  const accounts=await this.p.connection.getParsedTokenAccountsByOwner(new PublicKey(this.wallet),{mint:new PublicKey(USDC)},{commitment:'confirmed'});
  let walletUsdcRaw=0n;
  for(const a of accounts.value){const amount=a.account.data?.parsed?.info?.tokenAmount?.amount;if(typeof amount==='string')walletUsdcRaw+=BigInt(amount)}
  holdings??=await this.s.get('holdings',{});
  const trackedExposureRaw=BigInt(Object.values(holdings).reduce((n,h)=>n+(Number.isSafeInteger(h.costRaw)?h.costRaw:0),0));
  const equityRaw=walletUsdcRaw+trackedExposureRaw;
  const effectiveBankrollRaw=clamp(equityRaw,this.c.hardBudgetRaw);
  const s=strategy(),positionBps=BigInt(Math.max(1,Math.floor(s.livePositionPct*10000)));
  const maxOrderRaw=clamp(effectiveBankrollRaw*positionBps/10000n,this.c.hardMaxOrderRaw);
  const maxDailyRaw=clamp(effectiveBankrollRaw,this.c.hardMaxDailyRaw);
  const maxLossRaw=clamp(effectiveBankrollRaw/10n,this.c.hardMaxLossRaw);
  const portfolioRaw=effectiveBankrollRaw*15n/100n;
  return{walletUsdcRaw,trackedExposureRaw,equityRaw,effectiveBankrollRaw,maxOrderRaw,maxDailyRaw,maxLossRaw,portfolioRaw};
}

async readiness(){
  const orders=await this.s.orders(),holdings=await this.s.get('holdings',{}),r=await this.riskLimits(holdings);
  return{wallet:this.wallet,enabled:this.c.signerEnabled,checks:[...liveConfiguration(this.c),['Dedicated signing key loaded',!!this.key],['USDC bankroll available',r.effectiveBankrollRaw>0n],['Dynamic per-order limit',r.maxOrderRaw>0n],['Dynamic daily buy limit',r.maxDailyRaw>0n],['Dynamic daily loss limit',r.maxLossRaw>0n],['Kill switch clear',!(await this.s.get('killed',false))]],risk:{walletUsdc:asUsd(r.walletUsdcRaw),trackedExposureUsdc:asUsd(r.trackedExposureRaw),equityUsdc:asUsd(r.equityRaw),effectiveBankrollUsdc:asUsd(r.effectiveBankrollRaw),maxOrderUsdc:asUsd(r.maxOrderRaw),dailyBuyLimitUsdc:asUsd(r.maxDailyRaw),dailyLossLimitUsdc:asUsd(r.maxLossRaw),portfolioExposureLimitUsdc:asUsd(r.portfolioRaw)},unresolved:orders.filter(o=>['signed','submitted','unknown'].includes(o.state)).length};
}

public(o){return{id:o.id,state:o.state,signature:o.signature,at:o.at,result:o.result??null}}

async execute(intent){if(this.busy)throw Error('Signer busy');this.busy=true;try{const existing=await this.s.order(intent?.id);if(existing)return this.public(existing);const ready=await this.readiness();if(!ready.checks.every(x=>x[1]))throw Error('Live readiness gate not satisfied');const existingOrders=await this.s.orders();if(existingOrders.some(o=>['signed','submitted','unknown'].includes(o.state)))throw Error('Unresolved transaction blocks new orders');const holdings=await this.s.get('holdings',{}),risk=await this.riskLimits(holdings);validateIntent(intent,this.c,this.wallet,risk.maxOrderRaw);const buy=intent.inputMint===USDC,mint=buy?intent.outputMint:intent.inputMint,held=holdings[mint];if(!buy&&(!held||BigInt(intent.amount)>BigInt(held.raw)))throw Error('Exit exceeds reconciled tracked inventory');if(buy){const riskCheck=await inspect(mint,this.p);if(!riskCheck.allowed)throw Error('Fresh token risk check rejected entry: '+riskCheck.reasons.join(', '));const exposureRaw=BigInt(Object.values(holdings).reduce((n,h)=>n+h.costRaw,0));if(exposureRaw+BigInt(intent.amount)>risk.portfolioRaw)throw Error('Portfolio exposure limit');if(BigInt(await this.s.get('loss:'+new Date().toISOString().slice(0,10),0))>=risk.maxLossRaw)throw Error('Daily loss stop');await this.s.reserve(intent.id,Number(intent.amount),Number(risk.maxDailyRaw))}const q=await this.p.quote(intent.inputMint,intent.outputMint,intent.amount,this.wallet);validateQuote(q,intent,this.c,this.wallet);const tx=await validateTransaction(q,intent,this.c,this.wallet,this.p);if(Date.now()-q.observedAt>this.c.quoteAgeMs)throw Error('Quote expired during validation');if(await this.s.get('killed',false))throw Error('Kill switch enabled');tx.sign([this.key]);const signed=Buffer.from(tx.serialize()).toString('base64'),signature=bs58.encode(tx.signatures[0]);let o={id:intent.id,intent,state:'signed',signature,signed,quote:{requestId:q.requestId,otherAmountThreshold:q.otherAmountThreshold},at:Date.now()};await this.s.saveOrder(o);await this.s.event('SIGNED',{id:o.id,signature});try{const result=await this.p.execute(q,signed);if(result.signature&&result.signature!==signature)throw Error('Provider signature mismatch');o.state='submitted';await this.s.saveOrder(o)}catch{o.state='unknown';await this.s.saveOrder(o);await this.s.event('SUBMISSION_UNCERTAIN',{id:o.id,signature})}return this.public(o)}finally{this.busy=false}}

async reconcile(){if(this.busy)return;this.busy=true;try{for(const o of (await this.s.orders()).filter(o=>['signed','submitted','unknown'].includes(o.state))){const st=(await this.p.rpc('getSignatureStatuses',[[o.signature],{searchTransactionHistory:true}]))?.value?.[0];if(!st||st.confirmationStatus!=='finalized')continue;if(st.err){o.state='failed';await this.s.saveOrder(o);continue}const t=await this.p.rpc('getTransaction',[o.signature,{encoding:'jsonParsed',maxSupportedTransactionVersion:0,commitment:'finalized'}]);if(!t||t.meta.err)continue;const delta=new Map();for(const[field,sign]of[['preTokenBalances',-1n],['postTokenBalances',1n]])for(const b of t.meta[field]??[])if(b.owner===this.wallet)delta.set(b.mint,(delta.get(b.mint)??0n)+sign*BigInt(b.uiTokenAmount.amount));const spent=-(delta.get(o.intent.inputMint)??0n),received=delta.get(o.intent.outputMint)??0n;if(spent!==BigInt(o.intent.amount)||received<BigInt(o.quote.otherAmountThreshold)){await this.s.set('killed',true);await this.s.event('RECONCILIATION_MISMATCH',{id:o.id});continue}const holdings=await this.s.get('holdings',{}),buy=o.intent.inputMint===USDC,mint=buy?o.intent.outputMint:o.intent.inputMint;let pnl=0;if(buy){const h=holdings[mint]??{raw:'0',costRaw:0};h.raw=(BigInt(h.raw)+received).toString();h.costRaw+=Number(spent);holdings[mint]=h}else{const h=holdings[mint];if(!h||BigInt(h.raw)<spent){await this.s.set('killed',true);continue}const cost=Math.round(h.costRaw*Number(spent)/Number(h.raw));pnl=Number(received)-cost;h.raw=(BigInt(h.raw)-spent).toString();h.costRaw-=cost;if(h.raw==='0')delete holdings[mint];const day='loss:'+new Date().toISOString().slice(0,10);await this.s.set(day,(await this.s.get(day,0))+Math.max(0,-pnl))}await this.s.set('holdings',holdings);o.state='confirmed';o.result={spent:spent.toString(),received:received.toString(),pnlUSDC:pnl/1e6,networkFeeLamports:t.meta.fee,slot:t.slot};delete o.signed;await this.s.saveOrder(o);await this.s.event('FINALIZED_FILL',{id:o.id,signature:o.signature,...o.result})}}finally{this.busy=false}}
}
